title: Self-unemployed developer
author: Daniel Tombor
email: daniel@tmbr.me
description: > # this means to ignore newlines until "baseurl:"
  Diary of a self-unemployed developer's summer days. 
  Thoughts, notes, experiences and anecdotes about developer stuffs and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "danieltmbr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: "UA-100417263-1"

# Social profiles
social-profiles:
  - username: "danieltmbr"
    url: "https://github.com/danieltmbr"
    icon: "github"
    site: "GitHub"
  - username: "danieltmbr"
    url: "https://stackoverflow.com/users/3487134/danieltmbr"
    icon: "stackoverflow"
    site: "StackOverflow"
  - username: "danieltmbr"
    url: "https://twitter.com/danieltmbr"
    icon: "twitter"
    site: "Twitter"
  - username: "danieltmbr"
    url: "https://www.linkedin.com/in/danieltmbr/"
    icon: "linkedin"
    site: "LinkedIn"
    
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

permalink: pretty

# Pagination
paginate: 7
paginate_path: "/:num/"